//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsApp1 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorFondoApp {
            get {
                return ((global::System.Drawing.Color)(this["ColorFondoApp"]));
            }
            set {
                this["ColorFondoApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color ColorBotonFunciones {
            get {
                return ((global::System.Drawing.Color)(this["ColorBotonFunciones"]));
            }
            set {
                this["ColorBotonFunciones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorBotonNumeros {
            get {
                return ((global::System.Drawing.Color)(this["ColorBotonNumeros"]));
            }
            set {
                this["ColorBotonNumeros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImagenFondo {
            get {
                return ((string)(this["ImagenFondo"]));
            }
            set {
                this["ImagenFondo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 14pt, style=Bold")]
        public global::System.Drawing.Font TipoLetraTam {
            get {
                return ((global::System.Drawing.Font)(this["TipoLetraTam"]));
            }
            set {
                this["TipoLetraTam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorTextoBotonFun {
            get {
                return ((global::System.Drawing.Color)(this["ColorTextoBotonFun"]));
            }
            set {
                this["ColorTextoBotonFun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorTextoBotonNum {
            get {
                return ((global::System.Drawing.Color)(this["ColorTextoBotonNum"]));
            }
            set {
                this["ColorTextoBotonNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 0")]
        public global::System.Drawing.Color ColorBotonEspecial {
            get {
                return ((global::System.Drawing.Color)(this["ColorBotonEspecial"]));
            }
            set {
                this["ColorBotonEspecial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorTextoBotonEsp {
            get {
                return ((global::System.Drawing.Color)(this["ColorTextoBotonEsp"]));
            }
            set {
                this["ColorTextoBotonEsp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int OpcionFondo {
            get {
                return ((int)(this["OpcionFondo"]));
            }
            set {
                this["OpcionFondo"] = value;
            }
        }
    }
}
